In [36]:
import os
cwd = os.getcwd()
print(cwd)

/home/haodong/working/ds-ciss-policy-docs/task-b

In [37]:
mapL1 = {}
mapL2 = {}
trimLabel = lambda x: x.strip().split(' ')[0]
with open(os.path.join(cwd, 'mapping.csv')) as f:
    for line in f:
        line = line.strip().split(',')
        assert len(line) == 5
        labelL1, labelL2 = '', ''
        if len(line[3]) > 0:
            labelL1 = line[3]
        if len(line[4]) > 0:
            labelL2 = line[4]
        if len(line[0]) > 0:
            mapL1[trimLabel(line[0])] = labelL1
            mapL2[trimLabel(line[0])] = labelL2
        if len(line[1]) > 0:
            mapL1[trimLabel(line[1])] = labelL1
            mapL2[trimLabel(line[1])] = labelL2
        if len(line[2]) > 0:
            mapL1[trimLabel(line[2])] = labelL1
            mapL2[trimLabel(line[2])] = labelL2
len(mapL1), len(mapL2)

(1119, 1119)

In [38]:
import pandas as pd
df = pd.read_csv(os.path.join(cwd, 'policies_all.csv'))
df['type'] = df['type'].astype(str)
df.head()

,id,area,year,filename,url,type,dt
0,CLI.12.5637914,GuangXi,2021,2020年度南宁市文化广电和旅游业绩效考评公众评...(FBM-CLI.12.5637914...,https://www.pkulaw.com/lar/b239245cf42cbb8c56a...,旅游综合规定,2021.07.21
1,CLI.12.5499514,GuangXi,2021,《广西壮族自治区房屋建筑和市政基础设施工程...(FBM-CLI.12.5499514).txt,https://www.pkulaw.com/lar/3b23aa6caae81e8639b...,质量综合规定,2021.01.18
2,CLI.12.4155587,GuangXi,2021,万秀区人民政府关于印发《梧州市万秀区2021年秋...(FBM-CLI.12.4155587...,https://www.pkulaw.com/lar/4551997af834afe5d3b...,义务与基础教育,2021.05.08
3,CLI.12.6619567,GuangXi,2021,万秀区人民政府关于印发《梧州市万秀区进城务...(FBM-CLI.12.6619567).txt,https://www.pkulaw.com/lar/ad5bef084faa05e25a8...,教育综合规定,2021.12.23
4,CLI.12.6618484,GuangXi,2021,万秀区人民政府关于印发万秀区财政衔接推进乡...(FBM-CLI.12.6618484).txt,https://www.pkulaw.com/lar/fa2f81c0e6d4eab01fb...,财政综合规定,2021.11.29

In [39]:
# Documents with more than one label (splitted with a comma)
df[df['type'].apply(lambda x: len(x.split(','))) > 1]

,id,area,year,filename,url,type,dt
10799,CLI.12.1508801,GuangXi,2018,广西壮族自治区食品药品监督管理局关于改革完...(FBM-CLI.12.1508801).txt,https://www.pkulaw.com/lar/b10cd470ae1e53d768f...,"药品管理,营商环境优化",2018.01.23
10811,CLI.12.4180302,GuangXi,2018,德保县人民政府关于取消一批行政许可等事项的...(FBM-CLI.12.4180302).txt,https://www.pkulaw.com/lar/acfce2ae0754fe88fc1...,"机关工作综合规定,营商环境优化",2018.11.09
10814,CLI.12.4180282,GuangXi,2018,德保县人民政府关于进一步加强城市管理优化营...(FBM-CLI.12.4180282).txt,https://www.pkulaw.com/lar/d116bcb9c05f5696ab3...,"机关工作综合规定,营商环境优化",2018.11.27
10821,CLI.12.4191570,GuangXi,2018,德保县人民政府关于印发德保县治理车辆超限超...(FBM-CLI.12.4191570).txt,https://www.pkulaw.com/lar/e5194c846a05935afe9...,"机关工作综合规定,营商环境优化",2018.09.13
10825,CLI.12.4191571,GuangXi,2018,德保县人民政府办公室关于印发德保县统筹整合...(FBM-CLI.12.4191571).txt,https://www.pkulaw.com/lar/92ac08040ed75583ac3...,"财政综合规定,营商环境优化",2018.09.11
...,...,...,...,...,...,...,...
447759,CLI.12.897103,ShanXi,2013,晋城市民政局关于建立村(居)两委干部和低保经...(FBM-CLI.12.897103).txt,https://www.pkulaw.com/lar/2618f22cb17df55f03c...,"干部与工作人员,社会福利与社会保障",2013.06.04
447784,CLI.12.1945802,ShanXi,2013,晋城市环境保护局关于调整建设项目环境管理有...(FBM-CLI.12.1945802).txt,https://www.pkulaw.com/lar/2e9761f120152a1f52a...,"环保综合规定,营商环境优化",2013.12.30
447878,CLI.12.782498,ShanXi,2013,朔州市人民政府办公厅关于在全市非经营性互联...(FBM-CLI.12.782498).txt,https://www.pkulaw.com/lar/f863ed25d7a4ba0e4a0...,"网络安全管理,互联网",2013.06.17
447893,CLI.12.1951600,ShanXi,2013,运城市人力资源和社会保障局关于实行工作周报...(FBM-CLI.12.1951600).txt,https://www.pkulaw.com/lar/e44dc31bbf53cf49e3e...,"人事工资,起诉和受理",2013.09.26
447941,CLI.12.1942598,ShanXi,2013,运城市环境保护局印发《关于改进作风服务发展...(FBM-CLI.12.1942598).txt,https://www.pkulaw.com/lar/3925293e1e4054b4040...,"机关工作综合规定,营商环境优化",2013.04.22

In [40]:
# use the first label 
df['type'] = df['type'].apply(lambda x: x.split(',')[0])

In [41]:
df['label_L1'] = df['type'].map(mapL1)
df['label_L2'] = df['type'].map(mapL2)
df

,id,area,year,filename,url,type,dt,label_L1,label_L2
0,CLI.12.5637914,GuangXi,2021,2020年度南宁市文化广电和旅游业绩效考评公众评...(FBM-CLI.12.5637914...,https://www.pkulaw.com/lar/b239245cf42cbb8c56a...,旅游综合规定,2021.07.21,文化与科技,旅游
1,CLI.12.5499514,GuangXi,2021,《广西壮族自治区房屋建筑和市政基础设施工程...(FBM-CLI.12.5499514).txt,https://www.pkulaw.com/lar/3b23aa6caae81e8639b...,质量综合规定,2021.01.18,工业与建设,质量管理和监督
2,CLI.12.4155587,GuangXi,2021,万秀区人民政府关于印发《梧州市万秀区2021年秋...(FBM-CLI.12.4155587...,https://www.pkulaw.com/lar/4551997af834afe5d3b...,义务与基础教育,2021.05.08,社会事务与公共管理,教育
3,CLI.12.6619567,GuangXi,2021,万秀区人民政府关于印发《梧州市万秀区进城务...(FBM-CLI.12.6619567).txt,https://www.pkulaw.com/lar/ad5bef084faa05e25a8...,教育综合规定,2021.12.23,社会事务与公共管理,教育
4,CLI.12.6618484,GuangXi,2021,万秀区人民政府关于印发万秀区财政衔接推进乡...(FBM-CLI.12.6618484).txt,https://www.pkulaw.com/lar/fa2f81c0e6d4eab01fb...,财政综合规定,2021.11.29,经济与贸易,财政
...,...,...,...,...,...,...,...,...,...
448024,CLI.12.1886581,ShanXi,2013,阳泉市质量技术监督局关于认真做好《中华人民...(FBM-CLI.12.1886581).txt,https://www.pkulaw.com/lar/22399c9caea4a4a0089...,机关工作综合规定,2013.10.25,法律与司法,机关工作
448025,CLI.12.1891405,ShanXi,2013,阳泉市质量技术监督局关于调整阳泉市质量技术...(FBM-CLI.12.1891405).txt,https://www.pkulaw.com/lar/f45cebd08a7689e7eb2...,机关工作综合规定,2013.06.17,法律与司法,机关工作
448026,CLI.12.1886154,ShanXi,2013,阳泉市质量技术监督局关于转发市安委《关于转...(FBM-CLI.12.1886154).txt,https://www.pkulaw.com/lar/d0c14bc090860bf828f...,机关工作综合规定,2013.05.28,法律与司法,机关工作
448027,CLI.12.1886997,ShanXi,2013,阳泉市质量技术监督局关于转发省局《关于开展...(FBM-CLI.12.1886997).txt,https://www.pkulaw.com/lar/c6fe36a32d1ada9b250...,机关工作综合规定,2013.05.28,法律与司法,机关工作
448028,CLI.12.1885557,ShanXi,2013,阳泉市质量技术监督局关于转发省局《关于配合...(FBM-CLI.12.1885557).txt,https://www.pkulaw.com/lar/afe422e57ec8c5fea10...,机关工作综合规定,2013.05.28,法律与司法,机关工作

In [42]:
print("All records: {}. Record with no type (or 404): {}. Records with no L1 label: {}. Records with no L2 label: {}".format(len(df), len(df[(df['type'].isnull())|(df['type']=='404-NotFound')]), len(df[df['label_L1'].isnull()]), len(df[df['label_L2'].isnull()])))

All records: 448029. Record with no type (or 404): 827. Records with no L1 label: 2693. Records with no L2 label: 2693

In [43]:
df_noMap = df[~((df['type'] == 'nan') | (df['type']=='404-NotFound')) & df['label_L1'].isnull()].copy()
df_noMap.to_csv(os.path.join(cwd, 'policies_noMap.csv'), index=False)
df_noMap.shape

(1793, 9)

In [44]:
df_noMap

,id,area,year,filename,url,type,dt,label_L1,label_L2
10,CLI.12.6599289,GuangXi,2021,三江侗族自治县人民政府关于印发《三江侗族自...(FBM-CLI.12.6599289).txt,https://www.pkulaw.com/lar/52941b2f92eb07783cd...,机关工作综合规定营商环境优化,2021.07.28,NaN,NaN
18,CLI.12.6583069,GuangXi,2021,三江侗族自治县人民政府办公室关于调整三江侗...(FBM-CLI.12.6583069).txt,https://www.pkulaw.com/lar/072f17aa77f5222aaf4...,人事综合规定营商环境优化,2021.08.31,NaN,NaN
24,CLI.12.5742672,GuangXi,2021,上林县人民政府办公室关于印发上林县服务企业...(FBM-CLI.12.5742672).txt,https://www.pkulaw.com/lar/88a00a451134bbd1631...,机关工作综合规定营商环境优化,2021.12.08,NaN,NaN
29,CLI.12.5741786,GuangXi,2021,上林县人民政府办公室关于进一步明确上林县农...(FBM-CLI.12.5741786).txt,https://www.pkulaw.com/lar/dafb0932b4b290adaa1...,农业管理营商环境优化,2021.03.25,NaN,NaN
31,CLI.12.6422496,GuangXi,2021,东兰县人民政府关于印发《东兰县农村土地承包...(FBM-CLI.12.6422496).txt,https://www.pkulaw.com/lar/38457ca73009c0acffb...,土地综合规定营商环境优化,2021.12.25,NaN,NaN
...,...,...,...,...,...,...,...,...,...
426908,CLI.12.3909532,ShanXi,2016,阳泉市人民政府关于印发阳泉市“互联网 ”行...(FBM-CLI.12.3909532).txt,https://www.pkulaw.com/lar/7a63cdbb68bfd0a9768...,互联网+,2016.06.15,NaN,NaN
427328,CLI.12.5441324,BeiJing,2018,北京市老龄办关于邀请社会公众参加“老年人社...(FBM-CLI.12.5441324).txt,https://www.pkulaw.com/lar/10cf96efde40a6bf2c9...,民法通则,2018.07.27,NaN,NaN
427335,CLI.12.1511622,BeiJing,2018,北京市西城区人民政府办公室关于印发北京市西...(FBM-CLI.12.1511622).txt,https://www.pkulaw.com/lar/09d67b75466e95a8b26...,境内上市,2018.09.12,NaN,NaN
433381,CLI.12.1492062,JiLin,2018,吉林市人民政府关于促进新一代人工智能产业发...(FBM-CLI.12.1492062).txt,https://www.pkulaw.com/lar/8a32c41797a761ed164...,人工智能,2018.11.29,NaN,NaN
440352,CLI.12.1638083,ShanXi,2019,忻州市人民政府办公室关于做好复制推广自由贸...(FBM-CLI.12.1638083).txt,https://www.pkulaw.com/lar/c77d7402b970ba0ad83...,自由贸易试验区综合规定,2019.12.02,NaN,NaN

In [45]:
def matchLongest(x):
    res = ''
    x = x.strip()
    for key in mapL1:
        if x.startswith(key) and x[len(key):] in mapL1 and len(key) > len(res):
            res = key
    return res if res != '' else x
df_noMap['type'] = df_noMap['type'].apply(matchLongest)
df_noMap['label_L1'] = df_noMap['type'].map(mapL1)
df_noMap['label_L2'] = df_noMap['type'].map(mapL2)

In [46]:
df_noMap

,id,area,year,filename,url,type,dt,label_L1,label_L2
10,CLI.12.6599289,GuangXi,2021,三江侗族自治县人民政府关于印发《三江侗族自...(FBM-CLI.12.6599289).txt,https://www.pkulaw.com/lar/52941b2f92eb07783cd...,机关工作综合规定,2021.07.28,法律与司法,机关工作
18,CLI.12.6583069,GuangXi,2021,三江侗族自治县人民政府办公室关于调整三江侗...(FBM-CLI.12.6583069).txt,https://www.pkulaw.com/lar/072f17aa77f5222aaf4...,人事综合规定,2021.08.31,社会事务与公共管理,人事规定
24,CLI.12.5742672,GuangXi,2021,上林县人民政府办公室关于印发上林县服务企业...(FBM-CLI.12.5742672).txt,https://www.pkulaw.com/lar/88a00a451134bbd1631...,机关工作综合规定,2021.12.08,法律与司法,机关工作
29,CLI.12.5741786,GuangXi,2021,上林县人民政府办公室关于进一步明确上林县农...(FBM-CLI.12.5741786).txt,https://www.pkulaw.com/lar/dafb0932b4b290adaa1...,农业管理,2021.03.25,农业与自然资源,农业
31,CLI.12.6422496,GuangXi,2021,东兰县人民政府关于印发《东兰县农村土地承包...(FBM-CLI.12.6422496).txt,https://www.pkulaw.com/lar/38457ca73009c0acffb...,土地综合规定,2021.12.25,农业与自然资源,土地
...,...,...,...,...,...,...,...,...,...
426908,CLI.12.3909532,ShanXi,2016,阳泉市人民政府关于印发阳泉市“互联网 ”行...(FBM-CLI.12.3909532).txt,https://www.pkulaw.com/lar/7a63cdbb68bfd0a9768...,互联网+,2016.06.15,NaN,NaN
427328,CLI.12.5441324,BeiJing,2018,北京市老龄办关于邀请社会公众参加“老年人社...(FBM-CLI.12.5441324).txt,https://www.pkulaw.com/lar/10cf96efde40a6bf2c9...,民法通则,2018.07.27,NaN,NaN
427335,CLI.12.1511622,BeiJing,2018,北京市西城区人民政府办公室关于印发北京市西...(FBM-CLI.12.1511622).txt,https://www.pkulaw.com/lar/09d67b75466e95a8b26...,境内上市,2018.09.12,NaN,NaN
433381,CLI.12.1492062,JiLin,2018,吉林市人民政府关于促进新一代人工智能产业发...(FBM-CLI.12.1492062).txt,https://www.pkulaw.com/lar/8a32c41797a761ed164...,人工智能,2018.11.29,NaN,NaN
440352,CLI.12.1638083,ShanXi,2019,忻州市人民政府办公室关于做好复制推广自由贸...(FBM-CLI.12.1638083).txt,https://www.pkulaw.com/lar/c77d7402b970ba0ad83...,自由贸易试验区综合规定,2019.12.02,NaN,NaN

In [47]:
df.update(df_noMap)
df_noMap = df[~((df['type'] == 'nan') | (df['type']=='404-NotFound')) & df['label_L1'].isnull()].copy()
df.to_csv(os.path.join(cwd, 'policies_label.csv'), index=False)
df_noMap.to_csv(os.path.join(cwd, 'policies_noMap.csv'), index=False)
df_noMap.shape

(353, 9)